on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: yarn run test-all
      - name: Upload coverage to Codecov
        uses: ./
        with:
          files: ./coverage/calculator/coverage-final.json,./coverage/index/coverage-final.json
          file: ./coverage/coverage-final.json
          flags: unittest
          name: codecov-1
